{% set name = "arize-phoenix-evals" %}
{% set version = "3.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/arize_phoenix_evals-{{ version }}.tar.gz
  sha256: 949b2a750a54e91b8cb2116072372fec4ac55b65a7acaef624c625661b27b956

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<3.12
    - pandas
    - tqdm
    - typing-extensions >=4.5,<5
    - pystache
    - pydantic
    - jsonpath-ng
    - openinference-semantic-conventions
    - openinference-instrumentation
    - opentelemetry-api

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - phoenix.evals

about:
  summary: LLM Evaluations
  home: https://github.com/Arize-ai/phoenix/
  license: Elastic-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anticorrelator
    - axiomofjoy
    - michaelschiff
    - mikeldking
    - RogerHYang
