{% set name = "arize-phoenix-evals" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arize_phoenix_evals-{{ version }}.tar.gz
  sha256: bdb3924a8cf2c510a0f41e7b10253a93d71185455d7393781d5a685083a2ddc4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - hatchling
    - pip
  run:
    - python >=3.8,<3.12
    - pandas
    - tqdm
    - typing-extensions >=4.5,<5

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - phoenix.evals

about:
  summary: LLM Evaluations
  home: https://github.com/Arize-ai/phoenix/
  license: Elastic-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anticorrelator
    - axiomofjoy
    - michaelschiff
    - mikeldking
    - RogerHYang
