{% set name = "arize-phoenix-evals" %}
{% set version = "0.21.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/arize_phoenix_evals-{{ version }}.tar.gz
  sha256: d43d64215c2055537a42c3d30b6cc505c529ee06e75ecb9156e1e2189f6ff38d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<3.12
    - pandas
    - tqdm
    - typing-extensions >=4.5,<5

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - phoenix.evals

about:
  summary: LLM Evaluations
  home: https://github.com/Arize-ai/phoenix/
  license: Elastic-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anticorrelator
    - axiomofjoy
    - michaelschiff
    - mikeldking
    - RogerHYang
