{% set name = "arize-phoenix-evals" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/arize_phoenix_evals-{{ version }}.tar.gz
  sha256: 542380dfb9c4de726bd896c03c2bd4ec595e24b2465be4e3b74f5397a6f185ee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<3.12
    - pandas
    - tqdm
    - typing-extensions >=4.5,<5
    - pystache
    - pydantic
    - jsonpath-ng
    - openinference-semantic-conventions
    - opentelemetry-api

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - phoenix.evals

about:
  summary: LLM Evaluations
  home: https://github.com/Arize-ai/phoenix/
  license: Elastic-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - anticorrelator
    - axiomofjoy
    - michaelschiff
    - mikeldking
    - RogerHYang
